### ISSUE TITLE
Firefox shows the scrollbar where it shouldn't on Instagram

### ISSUE THREAD

**Issue by lerethel** [StylishThemes/Overlay-Scrollbars#11]
If a post contains more than one image, Firefox shows the scrollbar under the carousel. Turning the style off fixes the problem (the scrollbar disappears). The same happens if an account has a lot of highlights.

* **Browser**: Firefox 80.0.1
* **Operating System**: Windows 10 x64
* **Links to pages with the issue**:
Carousel: https://www.instagram.com/p/CFLWV13HIbS/
Highlights: https://www.instagram.com/seeker/
* **Screenshots**:
1. ![Screenshot_2020-09-19 Seeker on Instagram “Happy #HispanicHeritageMonth Today, we're spotlighting Dr Ellen Ochoa, an Americ](https://user-images.githubusercontent.com/32931827/93668754-66355b80-fa97-11ea-994d-7f08f6baa5b1.png)
2. ![Screenshot_2020-09-19 Seeker ( seeker) • Instagram photos and videos](https://user-images.githubusercontent.com/32931827/93668751-633a6b00-fa97-11ea-9e8d-fa24329e63a8.png)

**Comment by the-j0k3r** [comment]
Sadly on my current machine I cant even load any Instagram anything so cant load the affected areas CSS to inspect in order to devise a fix.

Also dont have an Instagram account and not going to create one if its needed, so Ill ask for help with anyone who can submit a PR

**Comment by the-j0k3r** [comment]
Well these Instagram classes are dynamically generated, so fixing now will break at next Instagram update.

![Capture](https://user-images.githubusercontent.com/31389848/93669238-fe7d1180-fa92-11ea-991b-35f9e26b0730.PNG)

I can exclude `[role="presentation"]` which will fix the issue, Bu I wonder if it will affect other sites other users visit.

@vednoc thoughts?

**Comment by vednoc** [comment]
> Well these Instagram classes are dynamically generated, so fixing now will break at next Instagram update.

Not necessarily, but they _will_ break at one point or another.


> I can exclude `[role="presentation"]` which will fix the issue, Bu I wonder if it will affect other sites other users visit.

Very likely to happen. I think a better workaround is to add Instagram-specific overrides in a new `@-moz-document` that will remove `scrollbar-width` on all elements with `[role="presentation"]` attribute.

**Comment by the-j0k3r** [comment]
Good point, @vednoc will use specific section overrides

**Comment by the-j0k3r** [comment]
Sadly this doesnt seem to get at it, the global override takes precedence still so instead a different specific local override is required. Basing fix on instagram css 

incoming

**Comment by vednoc** [comment]
I've used `scrollbar-width: none` while testing, but this seems to do the trick as well. :tada:

**Comment by lerethel** [comment]
Thanks! Sadly, the problem is still there if you open a carousel in a pop-up rather than a separate tab. It seems to be due to the fact that pop-ups are in a different element, not the `#react-root` one. You'll have to have an account to be able to open pics in pop-ups.

Here's a screenshot. Setting the highlighted element's `overflow-x` to `hidden` fixes the problem.

![Screenshot 2020-09-19 215607](https://user-images.githubusercontent.com/32931827/93687125-fd180d00-fac3-11ea-94b5-895d4f403578.jpg)

**Comment by lerethel** [comment]
> Sadly this doesnt seem to get at it, the global override takes precedence still so instead a different specific local override is required. Basing fix on instagram css
> 
> incoming

I just tried removing the rule for `#react-root`, and it worked for me, solving all three issues.

**Comment by the-j0k3r** [comment]
> I just tried removing the rule for #react-root, and it worked for me, solving all three issues.

I think you meant removing just #react-root from the rule, not the whole rule, will update, but in morning. thx for feedback

**Comment by the-j0k3r** [comment]
> I've used `scrollbar-width: none` while testing, but this seems to do the trick as well. tada

This removes all scrollbars that should exist, didnt work for me.

**Comment by the-j0k3r** [comment]
@athlonusm please [force update (click here)](https://raw.githubusercontent.com/StylishThemes/Overlay-Scrollbars/master/global-overlay-scrollbars.user.css)  to 3.0.4.

**Comment by lerethel** [comment]
The fix is working. Thanks!
