### ISSUE TITLE
Changing transparency does not seem to work anymore

### ISSUE THREAD

**Issue by prakharb5** [StylishThemes/Overlay-Scrollbars#12]
* **Browser**: Brave Browser v1.20.110 (Chromium 88.0.4324.192) and Edge Dev v90.0.803.0
* **Operating System**: Windows 10 19042.804
* **Link to page with the issue**: (all webpages)

The transparency color manager for the scrollbar thumbs and track have stopped working. 

![image](https://user-images.githubusercontent.com/51435948/109182255-cf419d80-77b2-11eb-9a4a-be1a1e9353ac.png)

Changing the transparency with the second seekbar does not seem to work anymore apparently. I even tried it with a fresh installation of Edge Dev channel, but I got the same result. 

Please help me.

**Comment by the-j0k3r** [comment]
Transparency works on hover for track  I cant remember if it ever worked on normal state as I dont actually use chromium based browser and testing was minimal when I did this style

In any case there's nothing we can do here about it, the variables are correctly set to the respective selectors, if something stopped working in more up-to date browsers chromium based or if somehow stylus itself causing this, I wouldn't know.

Nothing has changed in this style to cause any such issues, it would require more feedback from other users of the style on such browsers, maybe thers some advanced setting interfering, again I wouldn't know which, if any at all.

Tested in Version G chrome 88.0.4324.190 (Official Build) (64-bit)

@mottie maybe has some insight on whats going on here, hence the ping

**Comment by prakharb5** [comment]
I faced this in both up-to-date Brave browser stable version and (fresh install) Microsoft Edge Dev channel version :/

It used to work properly a few months back, I am facing this problem since a month now. 
When I first saw this problem in Edge Dev, I thought the browser is not compatible. Then I tried changing transparency in the extension in Brave browser, in which it used to work wonderfully. Apparently, changing the transparency broke it and now I cannot control transparency with slider :(

**Comment by the-j0k3r** [comment]
I looked at https://github.com/StylishThemes/Overlay-Scrollbars/issues/9 and it seems thats how it worked.

Also it seems that overlay scrollbars setting in Google chrome has been removed see https://www.reddit.com/r/chrome/comments/dsss44/bring_back_overlay_scrollbars_on_chromeflags/, if it affects how this style works, IDK.

It could be some setting or internal change in chromium that is making this conk out, lets wait until somone chimes in, which could be in the next 30 seconds or never sadly.

**Comment by prakharb5** [comment]
No, it used to work perfectly even without the need of overlay scrollbars in chrome flags.

> It could be some setting or internal change in chromium that is making this conk out

Possibly

> lets wait until somone chimes in, which could be in the next 30 seconds or never sadly.

😳🙁😔

**Comment by Mottie** [comment]
It looks like it might be a Stylus bug... I don't see the opacity included with the color variable. I'll open a ticket.

**Comment by Mottie** [comment]
Ok, not a stylus bug. We need to change the `@preprocessor` to `default` and remove the `:root` section

**Comment by prakharb5** [comment]
Perhaps a pull request?

**Comment by Mottie** [comment]
Fixed in v3.1.0

**Comment by prakharb5** [comment]
Thank you! Will check it out!

**Comment by the-j0k3r** [comment]
Ill assume then theres some issue with Stylus?

**Comment by Mottie** [comment]
https://github.com/openstyles/stylus/pull/1200

**Comment by the-j0k3r** [comment]
I dont understand the fix though, using css vars that arent defined anywhere makes no sense.

**Comment by silverwind** [comment]
The `default` preprocessor defines CSS vars from the style options. It's arguably the best solution as it does not rely on comments.

**Comment by the-j0k3r** [comment]
ah, well there are better ways to do this anyway.

Also not defining a preprocessor should be the same as the default preprocessor, or has this changed?

**Comment by Mottie** [comment]
See https://github.com/openstyles/stylus/wiki/Writing-UserCSS#default

> The default mode with standard CSS syntax external link is used if
>
> - `@preprocessor` default is set or
> - `@preprocessor` is missing and **no variable** is defined by `@var` or `@advanced`.

**Comment by the-j0k3r** [comment]
So no preprocessor same as preprocessor default

**Comment by Mottie** [comment]
No, if `@preprocessor` is undefined, it defaults to:
- `default` if there are _no_ `@var` or `@advanced`
-  `uso` if there are `@var` or `@advanced`

The PR I linked above just fixed `uso` mode to work with fractional opacities.
