### ISSUE TITLE
Overlays on top of a Youtube video (Horizontal)

### ISSUE THREAD

**Issue by erelado** [StylishThemes/Overlay-Scrollbars#8]
As a continuation of #6, when playing a Youtube video in fullscreen, I can see the scrollbar on the **bottom** at all times.

* **Browser**: Google Chrome Version 79.0.3945.88 (Official Build) (64-bit)
* **Operating System**: Windows 10
* **Link to page with the issue**: Youtube videos (Fullscreen)
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/20738487/71417787-eac18d80-266f-11ea-9f34-f70eaa492974.png)

**Comment by the-j0k3r** [comment]
I cant see anything of the sort, would you post an exact link and inspection screenshot so I can try and dupe this? AFAIK #6 solution fixed this.

Also pls ensure youre up to date style wise and that no other styles you have are causing this.

**Comment by erelado** [comment]
It occurs on ANY fullscreen video, and this is the only style I have enabled for Youtube.
![image](https://user-images.githubusercontent.com/20738487/71418127-8acbe680-2671-11ea-85a0-b5bebec99275.png)

**Comment by the-j0k3r** [comment]
I cant seem to be able to target this, ive disabled x overflow completely and it shows up still, only Linux side.

I guess Ill chalk this down to a chrome bug since disabling the overflow has no effect.

If you or anyone has some idea, please fell free to suggest something.

**Comment by the-j0k3r** [comment]
Actually removing the fix fr #6 fixes this, so its chrome something bug related.

**Comment by the-j0k3r** [comment]
update to v1.0.13 and see if that fixes it, if issue returns later Ill try to make this optional.

**Comment by erelado** [comment]
> update to v1.0.13 and see if that fixes it, if issue returns later Ill try to make this optional.

It did! Thank you  ever so much!
